### ISSUE TITLE
High CPU Usage when running the script

### ISSUE THREAD

**Issue by dchammond** [omikun/MyAppNap#14]
I wanted to try out this tool on Safari just to see how it works, however as these screenshots show, the script itself is using a lot more CPU power (and logically battery) than Safari does (and yes I know Safari probably already does AppNap). The first image is with the script running, second without. Also it tends to crash Safari once I kill the script.

<img width="279" alt="screen shot 2018-03-04 at 2 45 20 pm" src="https://user-images.githubusercontent.com/5134986/36950399-f8901f02-1fba-11e8-9c17-c5b83940927f.png">

<img width="278" alt="screen shot 2018-03-04 at 2 45 40 pm" src="https://user-images.githubusercontent.com/5134986/36950401-fc568234-1fba-11e8-8547-456cc71ea491.png">

**Comment by omikun** [comment]
Thanks for spotting that! I forgot the sleep statement after all the refactoring. It's fixed now.
