### ISSUE TITLE
Rumps system menu bar

### ISSUE THREAD

**Issue by paul-hammant** [omikun/MyAppNap#2]
See: https://github.com/jaredks/rumps

1) status reporting could be a phase 1 thing
2) phase 2 could be interactivity - a sub-menu pre-populated with apps to nap on some basis

**Comment by omikun** [comment]
Thanks! I'll take a look at it.

**Comment by omikun** [comment]
Check out Release v.4! It works pretty good, but I can't seem to get rid of the default quit option...
