### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [omikun/MyAppNap#23]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by blaise-io** [comment]
There's an icon in this screenshot, but I just see "FN" https://github.com/omikun/ForceNap/blob/master/ForceNap_screen_shot.png

**Comment by mansya** [comment]
I have design new logo for this project. do you like it ? what do you think ?

![force nap](https://user-images.githubusercontent.com/33461607/43482836-04c27b96-9534-11e8-937b-ae850a9c4fae.png)

**Comment by blaise-io** [comment]
@mansya Your icon does not convey napping or sleeping.

**Comment by mansya** [comment]
i will redesign a few more moments

**Comment by mansya** [comment]
I was repair my design. what do you think ? do you like it ?
![force nap](https://user-images.githubusercontent.com/33461607/43522269-150b9160-95c3-11e8-963a-4ab42b38f4de.png)
