### ISSUE TITLE
python in High sierra

### ISSUE THREAD

**Issue by masteranza** [omikun/MyAppNap#8]
In High Sierra I've got this:

`/usr/bin/python /Users/masteranza/Projects/MyAppNap/myAppNap.py Spotify
Monitoring Spotify, with PIDs: ['528', '607', '611', '612', '619']
Currently focused on iTerm2
Stopping Spotify
Traceback (most recent call last):
  File "/Users/masteranza/Projects/MyAppNap/myAppNap.py", line 64, in <module>
    os.kill(pid, signal.SIGSTOP)
TypeError: an integer is required`

A simple cast to int fixes the problem:
`os.kill(int(pid), signal.SIGCONT)`
`os.kill(int(pid), signal.SIGSTOP)`

**Comment by omikun** [comment]
Thanks! Fixed in 7792251
