### ISSUE TITLE
utf support

### ISSUE THREAD

**Issue by KrzysztofKowalski** [omikun/MyAppNap#9]
hi

i have this result when running:

```

~/workspace/MyAppNap> /usr/bin/python myAppNap.py Zdjęcia
Invalid app name, will not suspend/resume anything
        Will monitor apps in focus, switch to your desired app to see valid name
Currently focused on Terminal
myAppNap.py:53: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if last_active_app == desiredApp:

Currently focused on Zdjęcia # its photos app in polish

Currently focused on Terminal


^C
Exiting script
~/workspace/MyAppNap> /usr/bin/python myAppNap.py Trello 
Monitoring Trello, with PIDs: ['2018', '2019', '2028', '2030'] # multiple PIDs, not working then
Currently focused on Terminal
Stopping Trello
Traceback (most recent call last):
  File "myAppNap.py", line 64, in <module>
    os.kill(pid, signal.SIGSTOP)
TypeError: an integer is required
```

**Comment by PurpleMyst** [comment]
Hi. Could you please show the output of `myAppNap.py` when you focus on Trello? As in, does it print the name in your language or in English?

The second issue is already fixed in PRs #4 and/or #7, just a simple case of converting the output of `pgrep` to `int`s.

**Comment by KrzysztofKowalski** [comment]
its:

~/workspace/MyAppNap> /usr/bin/python myAppNap.py       
Invalid app name, will not suspend/resume anything
        Will monitor apps in focus, switch to your desired app to see valid name
Currently focused on Terminal
Currently focused on Zdjęcia
Currently focused on Trello
Currently focused on Terminal
^C
Exiting script

**Comment by PurpleMyst** [comment]
Ah, I've diagnosed the issue. We need to convert from bytes to UTF-8 strings.

I've tried fixing it in commit ac6a396 on [my fork](https://github.com/PurpleMyst/MyAppNap). Could you try what you've tried on this version on my fork?
